cache:
  directories:
  - "$HOME/.m2"
dist: bionic
sudo: false
language: generic
env:
- JAVA_HOME=$HOME/jdk PATH=$JAVA_HOME/bin:$PATH GRAALVM_VERSION="20.1.0" GRAALVM_JAVA_VERSION="11"
install:
- travis_retry wget --no-verbose -O $HOME/jdk.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
- mkdir $HOME/jdk && tar -xzf $HOME/jdk.tar.gz -C $HOME/jdk --strip-components=1
- "$HOME/jdk/bin/gu install native-image"
script:
- mvn package -B
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c63b86d201e7cd06bf86
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: releases
  api_key:
    secure: ROwTTzDoonpvuhmnbkmdjZp72ACwo0S46m2TB5RaSNaMNnraca4dCHaIYsNBoVw5S7Nt8A/XonwTrjzEr5eELshZ/eEz2NVy1tr1Ncb12kKoI2A6RLSGHqQCyiBf2zm3V1g4LFAXDQP7WK1lPiVipPl5NAQ8lQQp+QJ6F44y3N44vCwnyUltl2mGHJ/0wiERCITzWGr6hu9xe+jxBA/vhG3tmKulK1kSppWnSMktnmW1qPf397/BN9gfd7iLVTxBiC3Ng7R/hDHxf5sk54CXbvMwB51VpO9dDEO7jHdZndnhkk1+2Wb7okjPxctmulpjIWk3cqb4W1U8XVrgAk/coc4a5BeggTUI2VEATIGZcQzc8myYhif1O1H1R7uAXojlS7BLImHDhmJ6jIEIsybnOljCtcGag8Gj+dsD36r05Q9K8aJRRsj7mUqSZI5Xhds7kStS9LIVP16910GEpkW4Qv0lHUAe668nMv8elfG5KnaF3xx9+JvcNXzZu5tLpMPrAX68JYKDvjEN5LovKLH/oIYg5bVXEwIlozAINpZtrRTcWoIg1htwq8KlXv5CfVqENXOLpiuWeysavybkOrtfZkVm/EKzOo9M07Euiynjiaw/f3X2ZHT/AG4Uy3f4KOU5UDpKFsa0vpd879BYKYSI0i85nbG8RdQQau6gQONpgDI=
  file: 'component/yatta-component.jar'
  on:
    repo: yatta-lang/yatta
    tags: true
  skip_cleanup: 'true'
  overwrite: true
