cache:
  directories:
    - $HOME/.m2
dist: bionic
sudo: false
language: generic
env:
  - JAVA_HOME=$HOME/jdk PATH=$JAVA_HOME/bin:$PATH GRAALVM_VERSION="20.0.0" GRAALVM_JAVA_VERSION="11"
install:
  - wget -O $HOME/jdk.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz
  - mkdir $HOME/jdk && tar -xzf $HOME/jdk.tar.gz -C $HOME/jdk --strip-components=1
  - $HOME/jdk/bin/gu install native-image
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -pl -native -B -V
script:
  - mvn package
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c63b86d201e7cd06bf86
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
