cache:
  directories:
    - $HOME/.m2
dist: trusty
sudo: false
language: generic
env:
  - JAVA_HOME=$HOME/jdk PATH=$JAVA_HOME/bin:$PATH
install:
  - wget -O $HOME/jdk.tar.gz https://github.com/oracle/graal/releases/download/vm-19.0.0/graalvm-ce-linux-amd64-19.0.0.tar.gz
  - mkdir $HOME/jdk && tar -xzf $HOME/jdk.tar.gz -C $HOME/jdk --strip-components=1
  - gu install native-image
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
