cache:
  directories:
    - $HOME/.m2
dist: trusty
sudo: false
language: generic
env:
  - JAVA_HOME=$HOME/jdk PATH=$JAVA_HOME/bin:$PATH
install:
  - wget -O $HOME/jdk.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java11-linux-amd64-19.3.1.tar.gz
  - mkdir $HOME/jdk && tar -xzf $HOME/jdk.tar.gz -C $HOME/jdk --strip-components=1
  - gu install native-image
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c63b86d201e7cd06bf86
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
