name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: akovari/yatta
          tag_with_ref: true
          tags: latest
      - name: Notify gitter
        uses: juztcode/gitter-github-action@v1
        with:
          room-id: ${{ secrets.GITTER_ROOM_ID }}
          token: ${{ secrets.GITTER_TOKEN }}
          text: Docker image deployed to https://hub.docker.com/r/akovari/yatta
          message-id: ${{ steps.initial.outputs.message-id }}
