name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: 20.1.0.java11
      - name: Install native-package
        run: gu install native-image
      - uses: stCarolas/setup-maven@v3
        with:
          maven-version: 3.6.3
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Test
        run: mvn -B test
